Update DataFramesMeta blurb
JuliaData/DataFrames.jl pull request #2561
Opened 2020-11-26 20:50 UTC by pdeffebach

2020-11-26 21:58 UTC, bkamins commented on docs/src/man/querying_frameworks.md
> +When a DataFramesMeta macro such as `@select`, `@transform`, `@by`, `@combine`,
In DataFrames.jl we add .jl everywhere 😄 
```suggestion
When a DataFramesMeta.jl macro such as `@select`, `@transform`, `@by`, `@combine`, 
```

2020-11-26 21:58 UTC, bkamins commented
Nice that all else works. Can you also please update line https://github.com/JuliaData/DataFrames.jl/pull/2561/files#diff-bf486009121d3fe05fafd9375068dc724f89e44524d86f520e773c9933dd0b75R12 to refer to the current version of the package?

2020-11-26 22:01 UTC, bkamins requested changes
Also https://github.com/JuliaData/DataFrames.jl/pull/2561/files#diff-bf486009121d3fe05fafd9375068dc724f89e44524d86f520e773c9933dd0b75R94 produces a different row order (`transform` retains the original row order)

2020-11-27 14:39 UTC, pdeffebach commented
Sorry about that. should be fixed now.

2020-11-27 18:34 UTC, bkamins commented
> Sorry about that.

No problem. I know the pain of making PRs (and then @nalimilan makes a review and I often wonder how could I make some errors that he spots 😄).

Thank you!

2020-11-27 18:40 UTC, bkamins approved these changes

2020-11-27 18:40 UTC, merged